git:
  depth: 10
addons:
  homebrew:
    packages:
    - python # also installs python3 and pip3
    - upx
  apt:
    packages:
    - python3-dev
    - python3-pip #installs also python3
    - upx-ucl
    - python3-pyqt5 
    - pyqt5-dev-tools
    - qttools5-dev-tools


matrix:
  include:
  - name: "Xenial default"
    os: linux
    dist: xenial
  - name: "macOS with Homebrew"
    os: osx
  - name: "Xenial + python 3.8 // no miniconda"
    os: linux
    dist: xenial
    language: python
    python: 3.8
  - name: "PyLint"
    os: linux
    script:
    - find . -name '*.py' -print0 | xargs -0 python3 -m pylint

#TODO: switch to `conda` to test different Python versions on build matrix 
before_install:
# init correct installation environment here
  - true



install:
  - python3 -m pip install -U pip wheel setuptools
  - python3 -m pip install -r requirements_dev.txt

script:
  - python3 -m PyInstaller main.spec
after_script:
  - ls -la dist/*

deploy:
  name: maze-gui-gen $TRAVIS_TAG
  provider: releases
  file: dist/maze-gui-gen
  skip_cleanup: true
  draft: true
  api_key: $GITHUB_TOKEN
  on:
    python: 3.8
    # branch: travis-test
    tags: true
    